version: "3.9"
services:
  keycloak:
    build:
      context: keycloak
      dockerfile: Dockerfile
    container_name: demo-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command:
      - start-dev